---
- hosts: webservers
  gather_facts: yes
  tasks:
   - name: Update apt 
     become: yes
     apt:
      update_cache: yes
   - name: make sure Nginx is installed
     become: yes
     apt:
      name: nginx
      state: latest
   - name: make sure you install php-fpm
     become: yes
     apt:
      name: php7.4-fpm
      state: present
   - name: Nginx is intalled
     become: yes
     service:
         name: nginx
         state: started
   - name: php file is copied
     become: yes
     copy:
       src: index.php
       dest: /var/www/html/
   - name: template file is added
     become: yes
     template:
       src: nginx.conf
       dest: /etc/nginx/sites-available/default
   - name: Enable the configuration file from Nginx available sites
     become: yes
     file:
       src: /etc/nginx/sites-available/default
       dest: /etc/nginx/sites-enabled/default
       state: link
   - name: Web Servers restart
     become: yes
     service:
          name: nginx
          state: restarted

- hosts: haproxy
  gather_facts: yes
  vars:
    haproxy_mode: http
    haproxy_algorithm: roundrobin
    haproxy_backend: Web_servers
  become: yes
  tasks:
   - name: apt cache in Haproxy is updated
     apt:
      update_cache: yes
   - name: Hapoxy is installed
     become: yes
     apt:
      name: haproxy
      state: present
   - name: HAProxy config file is updated
     template:
      src: haproxy.cfg.j2
      dest: /etc/haproxy/haproxy.cfg
   - name: Restart HAProxy
     service:
       name: haproxy
       state: restarted
